---
- name: Install nginx server
  hosts: host1
  become: yes
  tasks:
    - apt:
        name: nginx
        state: present
        update_cache: yes
    - service:
        name: nginx
        state: started
        enabled: yes


      
